# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/simulations/POR/POR.gds
load POR
select top cell
flatten POR_flat
load POR_flat
cellname delete POR -noprompt
cellname rename POR_flat POR
select top cell
extract path /foss/designs/simulations/POR/output/POR__POR/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/simulations/POR/output/POR__POR/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/simulations/POR/output/POR__POR/magic_RC -o /foss/designs/simulations/POR/output/POR__POR/magic_RC/POR.pex.spice
quit -noprompt
