# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/simulations/LDO/LDO.gds
load LDO
select top cell
flatten LDO_flat
load LDO_flat
cellname delete LDO -noprompt
cellname rename LDO_flat LDO
select top cell
extract path /foss/designs/simulations/LDO/output/LDO__LDO/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/simulations/LDO/output/LDO__LDO/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/simulations/LDO/output/LDO__LDO/magic_RC -o /foss/designs/simulations/LDO/output/LDO__LDO/magic_RC/LDO.pex.spice
quit -noprompt
