# Generated by kpex 0.3.7
crashbackups stop
drc off
gds read /foss/designs/clock_final_2.gds
load clock_final_2
select top cell
flatten clock_final_2_flat
load clock_final_2_flat
cellname delete clock_final_2 -noprompt
cellname rename clock_final_2_flat clock_final_2
select top cell
extract path /foss/designs/output/clock_final_2__clock_final_2/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/output/clock_final_2__clock_final_2/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/output/clock_final_2__clock_final_2/magic_RC -o /foss/designs/output/clock_final_2__clock_final_2/magic_RC/clock_final_2.pex.spice
quit -noprompt
