# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/simulations/BGR/BGR.gds
load BGR
select top cell
flatten BGR_flat
load BGR_flat
cellname delete BGR -noprompt
cellname rename BGR_flat BGR
select top cell
extract path /foss/designs/simulations/BGR/output/BGR__BGR/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/simulations/BGR/output/BGR__BGR/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/simulations/BGR/output/BGR__BGR/magic_RC -o /foss/designs/simulations/BGR/output/BGR__BGR/magic_RC/BGR.pex.spice
quit -noprompt
